//! Experimental object protocol. Native lifecycle adapters never reuse an activation.
pub mod broker;
pub mod codegen;
pub mod contract;
pub mod draft;
pub mod error;
pub mod exports;
pub mod factories;
pub mod frame;
pub mod graph;
pub mod identity;
pub mod imports;
pub mod json;
pub mod lifecycle;
pub mod managed;
pub mod memory;
pub mod prepare;
pub mod runner_image;
pub mod sdk;
pub mod services;
pub mod session;
#[cfg(target_os = "linux")]
pub mod snapshot;
