//! Experimental object protocol. Native lifecycle adapters never reuse an activation.
pub mod broker;
pub mod codegen;
pub mod contract;
pub mod deployment;
pub mod draft;
pub mod error;
pub mod events;
pub mod exports;
pub mod factories;
pub mod frame;
pub mod graph;
pub mod host;
pub mod identity;
pub mod imports;
pub mod json;
pub mod lifecycle;
pub mod managed;
pub mod memory;
pub mod prepare;
#[cfg(target_os = "linux")]
pub mod process;
pub mod runner_image;
pub mod runtime;
pub mod sdk;
pub mod services;
pub mod session;
#[cfg(target_os = "linux")]
pub mod snapshot;
#[cfg(target_os = "linux")]
pub mod supervisor;
